import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignOutButton,
} from '@clerk/nextjs'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="mb-5 z-20">
          <SignedOut>
            <div className="flex flex-row-reverse m-2 z-20">
              <div className={`border-2 rounded-xl border-blue-950 px-2 z-20 mr-4`}>
            <SignInButton />
            </div>
            </div>
          </SignedOut>
          <SignedIn>
            <div className="flex justify-end gap-5 m-2 z-20">
            <div className="z-20">
            <UserButton />
            </div>
            <div className="border-2 rounded-xl border-r-2 px-2 h-7 z-20 mr-4">
            <SignOutButton/>
            </div>
            </div>
          </SignedIn>
        </header>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
